FROM node:20.11-alpine3.18

WORKDIR /app

RUN apk add --no-cache python3 make build-base

RUN npm install -g npm@latest

RUN npm install -g node-gyp

COPY package*.json ./


RUN npm install

COPY . .

RUN npx prisma generate

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]

